
language: php

php:
    - 7.0
    - 7.1
    - 7.2

services:
  - mysql
  - amqp
  - memcached
  - redis-server

before_script:
  - composer install
  - phpenv config-add .travis.ini
  - cp .travis.database.yml config/database.yml
  - mysql -e 'CREATE DATABASE test;'
  

## before_install:
  ## - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('')"
  ## - mysql -u root -e 'CREATE DATABASE test;'

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer install --no-interaction --prefer-dist

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover