
language: php

php:
    - 7.0
    - 7.1
    - 7.2

services:
  - mysql
  - memcached
  - mongodb
  - redis-server

before_script:
  - composer install
  - phpenv config-add .travis.ini
  - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('')"
  - mysql -e 'CREATE DATABASE test;'
  - wget http://pecl.php.net/get/mongodb-1.4.3.tgz tar -xzf mongodb-1.4.3.tgz
sh -c "cd mongodb-1.4.3 && phpize && ./configure && sudo make install"
echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`'

  ## - sleep 15
  ## - mongo mydb_test --eval 'db.createUser({user:"root",pwd:"test",roles:["readWrite"]});'

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer install --no-interaction --prefer-dist

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover