#!/usr/bin/env php
<?php
// console
// 
set_time_limit(0);
define('ROOT', __DIR__);

require 'vendor/autoload.php';

use Zend\ServiceManager\ServiceManager;
use Obullo\Mvc\Config\Loader\YamlLoader;
use Obullo\Mvc\Config\Cache\FileHandler;

use Dotenv\Dotenv;

if (false == isset($_SERVER['APP_ENV'])) {
    (new Dotenv(ROOT))->load();
}
$env = getenv('APP_ENV');

// -------------------------------------------------------------------
// Service Manager
// -------------------------------------------------------------------
//
$container = new ServiceManager;

$cacheHandler = new FileHandler('/var/cache/config/');

// To change default cache handler uncomment doc blocks and set your own.

// use Obullo\Mvc\Config\Cache\RedisHandler;
// $cacheHandler = new RedisHandler($container->get('redis'));

$loader = new YamlLoader($cacheHandler);

$env = getenv('APP_ENV');

// Put all config files here you want to load at bootstrap.

\Zend\Config\Factory::fromFiles(
    [
        ROOT.'/config/'.$env.'/database.yaml',
        ROOT.'/config/'.$env.'/monolog.yaml'
    ]
);
$container->setService('loader', $loader);
$container->setFactory('logger', 'Services\LoggerFactory');

use Symfony\Component\Console\Application;
use Command\DebugCommand;

$application = new Application();
$application->add(new DebugCommand);
$application->run();