
<?php $this->layout('template', ['title' => 'Welcome to easy to use Php Components']) ?>

<div class="welcome">

    <div class="header clearfix text-center">

      <p><a href=""><img src="<?php echo $this->asset('/images/logo.png') ?>"></a></p>

      <h4>Welcome to easy to use Php Components.</h4>
    </div>

  <p class="lead">If you are new to use <kbd>Obullo/Skeleton</kbd> please click below.</p>
  <p><a class="btn btn-lg btn-default" href="http://mvc.obullo.com/" role="button" target="_blank">Getting Started</a></p>

</div>