
# application
#    

framework:
    
    cookie:
        domain:
        path: /
        secure: false
        httpOnly: true
        expire: 0

    session:
        name: sessions
        
    translator:
        default_locale: 'en'